### ISSUE TITLE
Filenames of `x86_86_asm.docset` contain `:`, incompatible with Windows

### ISSUE THREAD

**Issue by sighingnow** [Kira-cxy/pwn-dash-docset#1]
Some filenames of x86_64_asm docs contains `:`, such filename is invalid on windows.

**Comment by 0xKira** [comment]
I failed to consider that there are Windows users. I'm trying to fix it.

**Comment by 0xKira** [comment]
I rename the files. Please check the newest version. @sighingnow

**Comment by sighingnow** [comment]
Many thanks for doing that!
